### PR TITLE
ul and ol style in the wrong section

### PR DESCRIPTION
**Pull request by stephanerosi**

### CODE REVIEW

**Comment by nicolas-owp** [comment]
Hello, I've misunderstood what do you mean by the wrong section?

**Comment by stephanerosi** [comment]
Before
image

After
image

**Comment by stephanerosi** [comment]
Looks like the ol and ul style was defined in the wrong lines (line 7425 instead of 7399)

**Comment by stephanerosi** [comment]
The page above can be found here : http://vmeh-92.info/index.php/2018/10/21/prochaines-reunions-du-conseil/

**Comment by nicolas-owp** [comment]
Ah yes, thanks a lot, added in the next release :)

**Comment by stephanerosi** [comment]
@nicolas-owp You're welcome!

**Pull request closed without merging**
