### PR TITLE
Protection from email harvesters

### PR DESCRIPTION
**Pull request by taliesinpenbardd**
See https://codex.wordpress.org/Protection_From_Harvesters#Disguising_Your_Email

### CODE REVIEW

**Comment by nicolas-owp** [comment]
Hello, I cannot implement this in the core because most users want to display a normal email format, but it is easy to do this via a child theme.

**Comment by taliesinpenbardd** [comment]
Quoting the Codex page : « A slightly more complicated approach is to transform or encode characters in an address to their HTML character entity, or numeric character reference, equivalent. This means the letter a in an address becomes &#97;, the @ symbol &#64;, and so on. These should appear as gobbledygook to harvesters, while your browser renders them correctly. »

It is printed like a "normal" email address, it's just the encoding that is scrambled. But I should have scanned for all the code portions that display an email address, and my code lacks the "echo" needed, because `antispambot()` just returns the obfuscated email.

**Comment by nicolas-owp** [comment]
You're right, thank you very much for that, I will add it for the next release :)

**Comment by taliesinpenbardd** [comment]
De rien ;)

**Pull request closed without merging**
