### PR TITLE
Added support for WooCommerce Match Box single product layout.

### PR DESCRIPTION
**Pull request by seb86**
This corrects the single product layout for Mix and Match Products when WooCommerce Match Box extension is used.

### CODE REVIEW

**Comment by GAPP99** [comment]
Just wanted to support this plugin. I have been using it for 6 months.

**Comment by seb86** [comment]
@oceanwp Have you had a chance to look at this yet? It supports my WooCommerce extension with your theme. Besides the version that now needs updating in the comment this pull is ready. If you have any questions let me know. Thank you.

**Comment by oceanwp** [comment]
Hello @seb86, sorry, I had not seen :)
Can I try your plugin to see if everything is ok?
Thank you.

**Comment by seb86** [comment]
Sure @oceanwp. I will give you repository access. I'm currently finishing a new release which includes the action hook for this pull request to work so you will have to download the master branch. Will be pushing more code later tonight.

**Comment by seb86** [comment]
Your welcome. You just need to update the correct version that my function was introduced.

**Pull request merged**
