### PR TITLE
Added support for Auto Load Next Post

### PR DESCRIPTION
**Pull request by seb86**

### CODE REVIEW

**Comment by nicolas-owp** [comment]
Hello @seb86, I'm very sorry for the late answer, I was working on many things at the same time, so what you propose is the ability to load the next post when we are on a single post, that's right?
I was planned to do something like that in a plugin with other cool features for blog.
Thank you.

**Comment by seb86** [comment]
@nicolas-owp That's OK. I'm glad you got round to seeing my pull request.

> so what you propose is the ability to load the next post when we are on a single post, that's right?

Yes, that is correct. I have corrected the conflicts so you should be able to merge them now.

**Comment by nicolas-owp** [comment]
Hello, thanks a lot :)
So it works out of the box? The users will just need to activate a setting on their customizer, and they will be able to load the next post on their single post, right?
Thank you.

**Comment by seb86** [comment]
They just need to have ALNP installed and activated. It will then read the theme support that I have added here and my plugin will set the settings automatically.

**Comment by seb86** [comment]
The users do not need to do anything else to setup. Other settings are optional.

**Comment by nicolas-owp** [comment]
Thank you :)

**Comment by nicolas-owp** [comment]
By cons, I removed the recommendation of your plugin, I just added the compatibility, I recommend only three plugins.

**Comment by nicolas-owp** [comment]
I just tried to install the plugin, I have created two posts and when I am on a post, it doesn't load the next post, what I'm doing wrong?
If it doesn't work out of the box, I will not be able to support it in OceanWP.

**Comment by nicolas-owp** [comment]
Hi, I have deleted the support because I needed to update my theme and as ALNP doesn't work as it should in my case, it is better to add it for another release.

**Comment by seb86** [comment]
It was working fine when I tested before submitting my pull request and there have not been any further updates to the plugin. Can you tell me what steps you did exactly so that I can replicate?

Did you get a notice saying that your theme is supported when activating ALNP?

**Comment by nicolas-owp** [comment]
Hi, I just moved the files, I added them directly in the third folder, and the second file still in the third folder but inside a inc folder, then I edited the path in the functions.php and the first file, and yes, I had the notice that say that OceanWP is compatible so it was working, I tried to check the result, I have creetd two posts, but when I was on one of the post, it didn't redirect me to the second.

**Comment by seb86** [comment]
It does not redirect, it loads the next post at the end of the previous post. You just scroll down. Do you have a live demo site I can see or was it local?

**Comment by nicolas-owp** [comment]
Yes, sorry, I meant by redirect, it doesn't load the second post at the end of the first post.
Yes, it was locally.
You can just add the files inside the third folder and to call the class in the "include_functions()" function in the functions.php file, then for your second file, add it in a new folder named "inc" still inside the third folder, if it works for you, there is a problem because it was not working for me, no error in the console, so no JS conflict.

**Comment by seb86** [comment]
@nicolas-owp Sorry for responding back so late. When you tested with just 2 posts it's possible you loaded the oldest post first. Auto Load Next Post loads in descending order from the initial post the visitor started reading from so if you have no other posts it's not going to do anything. It's better to test Auto Load Next Post with more than 2 posts. Was this the only reason it was not accepted? If so, would you like me to make another pull request?

**Comment by nicolas-owp** [comment]
Hello @seb86, yes, please, could you make another request? I will re-test it and if everything works correctly, it will be added for the next release.
Thank you.

**Comment by seb86** [comment]
@nicolas-owp Thank you for getting back to me. I don't know when I will have time to make another push at this time since you took a while to respond but will keep you informed when I do. Currently improving support for the plugin and writing clearer [documentation](https://github.com/autoloadnextpost/alnp-documentation). Would be a great help if you could look over the documentation and let me know if you understand it when you have the time.

**Comment by nicolas-owp** [comment]
Hello, no problem, do it when you will have time.
Sorry for my late answer, I was working on many things at the same time.

**Comment by seb86** [comment]
Hi @nicolas-owp 

I decided to add the support directly in the plugin now that I have a better way to manage theme support. Thank you for assisting me.

**Comment by nicolas-owp** [comment]
Hello, even better :)

**Pull request merged**
