### PR TITLE
Rank Math SEO Compatibility

### PR DESCRIPTION
**Pull request by MyThemeShop**
It seems like many users are asking in our forums which are using your theme to add compatibility, especially of the Breadcrumbs. These changes add the compatibility of the plugin.

### CODE REVIEW

**Comment by nicolas-owp** [comment]
Hello, thanks a lot, I didn't directly add it as some classes have been moved but it is added for the next release.

**Comment by MyThemeShop** [comment]
Hello @nicolas-owp 

Sure. Can you please update this ticket once you add the compatibility or did you add it already?

If so, we can feature you on our website and add a dofollow backlink:
https://rankmath.com/compatibility/

Looking forward to hearing from you soon. Thank you.

**Comment by nicolas-owp** [comment]
Hello, it is added on GitHub: https://github.com/oceanwp/oceanwp/blob/master/inc/breadcrumbs.php#L58
But not the official release yet as I have more work to do before update the theme.

**Comment by MyThemeShop** [comment]
Hello, 

Thank you for the update.

Can you please update here once you release so we can announce in our channels as well and bring you much needed attention from our users?

Thank you.

**Comment by nicolas-owp** [comment]
Hi, it is already in the theme so on the next release, it will be integrated :)

**Pull request closed without merging**
